#!/bin/sh
# Copyright (C) 2012  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: http://www.pitt-pladdy.com/blog/_20121016-200723_0100_iostat_on_Cacti_via_SNMP/
#
# Version 20130412
#
# Thanks to:
#	"Tim" - readlink error diagnosis

STATSFILE=/var/local/snmp/iostat



findmountpoint () {
	while read line; do
		dev=`echo $line | cut -d' ' -f1`
		path=`echo $line | cut -d' ' -f2`
		devshort=`echo $dev | sed 's/^.*\///'`
		if [ $1 = $devshort ]; then
			echo $path
			return
		fi
		# no match on device (direct) - check for symlinks
		echo $dev | grep -q '^-' && continue
		link=`readlink $dev`
		if [ ! -z "$link" ]; then
			devshort=`echo $link | sed 's/^.*\///'`
			if [ $1 = $devshort ]; then
				echo Mounted on $path
				return
			fi
		fi
	done </proc/mounts
	echo Not mounted
}


if [ $1 != 'mountpoint' ]; then
	cut -d' ' -f$1 $STATSFILE
else
	for dev in `cut -d' ' -f1 $STATSFILE`; do
		findmountpoint $dev
	done
fi
