#!/bin/sh
# Copyright (C) 2012  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: http://www.pitt-pladdy.com/blog/_20121016-200723_0100_iostat_on_Cacti_via_SNMP/
#
# Version 20130711


/usr/bin/iostat -Ndkx 300 2 \
	| /usr/bin/tail -n+4 \
	| /bin/grep -A 1000 Device \
	| /usr/bin/tail -n+2 \
	| /usr/bin/head -n-1 \
	| /bin/sed 's/  */ /g' \
	> $1.tmp$$
mv $1.tmp$$ $1
# get the mountpoints cached
for dev in `cut -d' ' -f1 $1`; do
	path=`grep ^/dev/ /proc/mounts | grep -m  1 "^/[^ ]*/$dev " | cut -d' ' -f2`
	if [ ! -z "$path" ]; then
		echo $path >>$1-mountpoints.tmp$$
		continue
	fi
	# deeper search - look for symlinks to this device
	path='Not mounted'
	for mountdev in `grep ^/dev/ /proc/mounts | cut -d' ' -f1`; do
		[ -h "$mountdev" ] && readlink -f "$mountdev" | grep -q /$dev$ || continue
		mountdevshort=`echo $mountdev | sed 's/^.*\///'`
		path=`grep ^/dev/ /proc/mounts | grep -m 1 "^/[^ ]*/$mountdevshort " | cut -d' ' -f2`
		if [ -z "$path" ]; then
			path='Not mounted'
		fi
		break
	done
	echo $path >>$1-mountpoints.tmp$$
done
mv $1-mountpoints.tmp$$ $1-mountpoints


