#!/bin/sh
# Copyright (C) 2012  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: http://www.pitt-pladdy.com/blog/_20121016-200723_0100_iostat_on_Cacti_via_SNMP/
#
# Version 20121028

findmountpoint () {
	while read line; do
		dev=`/bin/echo $line | cut -d' ' -f1`
		path=`/bin/echo $line | cut -d' ' -f2`
		devshort=`/bin/echo $dev | sed 's/^.*\///'`
		if [ $1 = $devshort ]; then
			/bin/echo $path
			return
		fi
		link=`readlink $dev`
		if [ ! -z $link ]; then
			devshort=`/bin/echo $link | sed 's/^.*\///'`
			if [ $1 = $devshort ]; then
				/bin/echo Mounted on $path
				return
			fi
		fi
	done </proc/mounts
	/bin/echo Not mounted
}


if [ $1 != 'mountpoint' ]; then
	/usr/bin/cut -d' ' -f$1 /var/local/snmp/iostat
else
	for dev in `/usr/bin/cut -d' ' -f1 /var/local/snmp/iostat`; do
		findmountpoint $dev
	done
fi
